name: composite action test
on: pull_request
jobs:
  composite-test:
    runs-on: ubuntu-latest
    steps:
      - uses: nukokusa/koyomi@v1
        with:
          version: 0.1.5
      - run: |
          which koyomi
          koyomi --help
